name: build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            - name: Set env
              run: |
                echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
                echo "DOTNET_hostBuilder:reloadConfigOnChange=false" >> $GITHUB_ENV
            - uses: dotnet/nbgv@master
              id: nbgv
            - name: Clean
              run: |
                dotnet clean ./BotSharp.sln --configuration Release
                dotnet nuget locals all --clear
            - name: Build
              run: dotnet build -c Debug
            - name: Run MySQL
              run: |
                cp tests/UnitTest/mysql.cnf ~/.my.cnf
                sudo systemctl start mysql.service
                mysql -e "SET PERSIST binlog_row_metadata = 'FULL';" -uroot -proot
                mysql -e 'CREATE DATABASE garden;USE garden;CREATE TABLE pet (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(20), owner VARCHAR(20), species VARCHAR(20), sex CHAR(1), birth DATE, death DATE, timeUpdated datetime);' -uroot -proot
            - name: Test
              run: |
                cd tests/UnitTest
                dotnet test